GET http://localhost:9080/dukes-data/api/greetings
Accept: application/json, text/plain

###
POST http://localhost:9080/dukes-data/api/greetings
Content-Type: application/json

{
  "message": "Hello from JavaOne",
  "name": "Duke"
}
